version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branch:
      only: -master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:93:70:ad:2e:87:27:4c:a3:0e:88:5e:36:68:c4:80"
      - checkout
      - restore_cache:
          keys:
            - node_modules
      - run: echo "A first hello"
      - run: npm -v
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node_modules
      - run:
          name: Build
          command: yarn build
      - run:
          name: Prepare
          # shell chmod+x 赋予权限
          command: chmod +x scripts/deploy.sh
      - run:
          name: Deploy
          # 执行shell脚本
          command: ./scripts/deploy.sh
